# Generated by Django 3.0 on 2020-11-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201127_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Auriculares'), ('F', 'Forros'), ('VT', 'Vidrio Templado'), ('C', 'Cargador'), ('CU', 'Cable USB'), ('AD', 'Adaptadores')], default='A', max_length=2),
        ),
    ]
