# Generated by Django 3.0 on 2020-11-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201129_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(default='../static_in_env/img/no-photo-available.png', max_length=2083),
        ),
    ]
