# Generated by Django 3.0 on 2020-12-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default="This is one of the quality items we sell here in our store. Resistant, high-end quality materials. Only the best for our precious iPhone 12 Pro. You can stun Goku with one hit and with two theres a posibility of a K.O. Give it a try, you won't regret. Be Smart. Be Cool. Be the greatest."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
